-- AlterTable
ALTER TABLE `user` ADD COLUMN `otpExperied` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `otpVerify` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `resetOtp` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `resetOtpExperied` INTEGER NOT NULL DEFAULT 0;
